from __future__ import annotations

from typing import Any, Iterable

import pandas as pd

from config import Config
from services.market_data_service import (
    MarketDataService,
    get_market_data_service,
)
from utils.helpers import (
    normalize_symbol,
    safe_float,
)
from utils.logger import (
    get_logger,
    log_exception,
)


logger = get_logger(
    "services.technical_metrics_service"
)


# ============================================================
# ERROR
# ============================================================


class TechnicalMetricsError(
    RuntimeError
):
    """
    Raised when verified technical metrics
    cannot be created.

    IMPORTANT:
    No fake or fabricated market metrics
    are generated by this service.
    """


# ============================================================
# TECHNICAL METRICS SERVICE
# ============================================================


class TechnicalMetricsService:
    """
    Builds verified technical metrics used by:

    1. Sector ranking
    2. Top-stock ranking
    3. Relative-strength ranking
    4. Candidate-universe creation

    ----------------------------------------------------------
    FINAL EAGLE FLOW
    ----------------------------------------------------------

    NSE universe
        ↓
    FYERS verified candles
        ↓
    Technical metrics
        ↓
    Top 10 sectors
        ↓
    Top 10 stocks per sector
        ↓
    Maximum 100 candidate stocks
        ↓
    Final technical scanner
        ↓
    STRONG BUY only

    ----------------------------------------------------------
    IMPORTANT
    ----------------------------------------------------------

    This service DOES NOT itself generate STRONG BUY.

    Final STRONG BUY confirmation belongs to:

        scanners/technical_scanner.py

    This service only produces ranking metrics.

    No fundamental analysis.
    No fake values.
    No synthetic OHLCV data.
    """

    # ========================================================
    # INIT
    # ========================================================

    def __init__(
        self,
        *,
        market_data_service: (
            MarketDataService | None
        ) = None,
    ) -> None:

        self.market_data_service = (
            market_data_service
            or get_market_data_service()
        )

    # ========================================================
    # EMA
    # ========================================================

    @staticmethod
    def _ema(
        series: pd.Series,
        period: int,
    ) -> pd.Series:

        if series.empty:
            return pd.Series(
                dtype="float64"
            )

        return (
            series
            .ewm(
                span=int(
                    period
                ),
                adjust=False,
            )
            .mean()
        )

    # ========================================================
    # RSI
    # ========================================================

    @staticmethod
    def _rsi(
        series: pd.Series,
        period: int,
    ) -> pd.Series:

        if series.empty:

            return pd.Series(
                dtype="float64"
            )

        delta = (
            series.diff()
        )

        gain = (
            delta.clip(
                lower=0
            )
        )

        loss = (
            -delta.clip(
                upper=0
            )
        )

        average_gain = (
            gain
            .ewm(
                alpha=(
                    1.0
                    / float(
                        period
                    )
                ),
                adjust=False,
            )
            .mean()
        )

        average_loss = (
            loss
            .ewm(
                alpha=(
                    1.0
                    / float(
                        period
                    )
                ),
                adjust=False,
            )
            .mean()
        )

        safe_average_loss = (
            average_loss.replace(
                0.0,
                float("nan"),
            )
        )

        relative_strength = (
            average_gain
            / safe_average_loss
        )

        rsi = (
            100.0
            - (
                100.0
                / (
                    1.0
                    + relative_strength
                )
            )
        )

        # RSI may legitimately reach 100
        # when average loss is zero.
        zero_loss_mask = (
            average_loss
            == 0.0
        )

        positive_gain_mask = (
            average_gain
            > 0.0
        )

        rsi = rsi.mask(
            (
                zero_loss_mask
                & positive_gain_mask
            ),
            100.0,
        )

        flat_mask = (
            (
                average_gain
                == 0.0
            )
            & (
                average_loss
                == 0.0
            )
        )

        rsi = rsi.mask(
            flat_mask,
            50.0,
        )

        return rsi

    # ========================================================
    # CHANGE %
    # ========================================================

    @staticmethod
    def _change_percent(
        current: float,
        previous: float,
    ) -> float:

        if (
            current <= 0
            or previous <= 0
        ):
            return 0.0

        return (
            (
                current
                / previous
            )
            - 1.0
        ) * 100.0

    # ========================================================
    # DATAFRAME
    # ========================================================

    @staticmethod
    def _build_dataframe(
        candles: list[
            dict[str, Any]
        ],
    ) -> pd.DataFrame:

        if not isinstance(
            candles,
            list,
        ):

            raise (
                TechnicalMetricsError(
                    (
                        "Verified candle data "
                        "must be a list."
                    )
                )
            )

        if not candles:

            raise (
                TechnicalMetricsError(
                    (
                        "Verified candle data "
                        "is unavailable."
                    )
                )
            )

        dataframe = pd.DataFrame(
            candles
        )

        required_columns = {
            "open",
            "high",
            "low",
            "close",
            "volume",
        }

        if not (
            required_columns
            .issubset(
                dataframe.columns
            )
        ):

            raise (
                TechnicalMetricsError(
                    (
                        "Required OHLCV "
                        "columns are missing."
                    )
                )
            )

        # ----------------------------------------------------
        # TIMESTAMP
        # ----------------------------------------------------

        if (
            "timestamp"
            in dataframe.columns
        ):

            dataframe[
                "timestamp"
            ] = pd.to_numeric(
                dataframe[
                    "timestamp"
                ],
                errors="coerce",
            )

        # ----------------------------------------------------
        # OHLCV
        # ----------------------------------------------------

        for column in (
            "open",
            "high",
            "low",
            "close",
            "volume",
        ):

            dataframe[
                column
            ] = pd.to_numeric(
                dataframe[
                    column
                ],
                errors="coerce",
            )

        dataframe = (
            dataframe
            .dropna(
                subset=[
                    "open",
                    "high",
                    "low",
                    "close",
                ]
            )
            .copy()
        )

        dataframe[
            "volume"
        ] = (
            dataframe[
                "volume"
            ]
            .fillna(
                0.0
            )
        )

        # ----------------------------------------------------
        # REMOVE INVALID PRICE ROWS
        # ----------------------------------------------------

        dataframe = dataframe[
            (
                dataframe[
                    "open"
                ]
                > 0
            )
            & (
                dataframe[
                    "high"
                ]
                > 0
            )
            & (
                dataframe[
                    "low"
                ]
                > 0
            )
            & (
                dataframe[
                    "close"
                ]
                > 0
            )
        ].copy()

        # ----------------------------------------------------
        # OHLC VALIDATION
        # ----------------------------------------------------

        dataframe = dataframe[
            (
                dataframe[
                    "high"
                ]
                >= dataframe[
                    [
                        "open",
                        "close",
                        "low",
                    ]
                ]
                .max(
                    axis=1
                )
            )
            & (
                dataframe[
                    "low"
                ]
                <= dataframe[
                    [
                        "open",
                        "close",
                        "high",
                    ]
                ]
                .min(
                    axis=1
                )
            )
        ].copy()

        dataframe = dataframe[
            dataframe[
                "volume"
            ]
            >= 0
        ].copy()

        # ----------------------------------------------------
        # SORT / DEDUPLICATE
        # ----------------------------------------------------

        if (
            "timestamp"
            in dataframe.columns
        ):

            dataframe = (
                dataframe
                .dropna(
                    subset=[
                        "timestamp"
                    ]
                )
                .drop_duplicates(
                    subset=[
                        "timestamp"
                    ],
                    keep="last",
                )
                .sort_values(
                    by="timestamp"
                )
            )

        dataframe = (
            dataframe
            .reset_index(
                drop=True
            )
        )

        # ----------------------------------------------------
        # MINIMUM REQUIRED
        # ----------------------------------------------------

        minimum_required = max(
            int(
                Config.EMA_LONG
            ),
            int(
                Config.VOLUME_AVG_PERIOD
            ),
            int(
                Config.RSI_PERIOD
            )
            + 1,
            21,
        )

        if (
            len(
                dataframe
            )
            < minimum_required
        ):

            raise (
                TechnicalMetricsError(
                    (
                        "Insufficient verified "
                        "candles. "
                        f"{len(dataframe)} available; "
                        f"{minimum_required} required."
                    )
                )
            )

        return dataframe

    # ========================================================
    # SAFE SERIES VALUE
    # ========================================================

    @staticmethod
    def _series_value(
        series: pd.Series,
        position: int = -1,
    ) -> float:

        try:

            value = safe_float(
                series.iloc[
                    position
                ]
            )

        except (
            IndexError,
            TypeError,
        ):

            value = None

        if value is None:
            return 0.0

        return float(
            value
        )

    # ========================================================
    # BUILD METRICS FROM VERIFIED CANDLES
    # ========================================================

    def build_metrics_from_candles(
        self,
        *,
        symbol: str,
        candles: list[
            dict[str, Any]
        ],
        benchmark_change_pct: float = 0.0,
    ) -> dict[str, Any]:

        normalized_symbol = (
            normalize_symbol(
                symbol
            )
        )

        if not normalized_symbol:

            raise ValueError(
                (
                    "Valid stock symbol "
                    "is required."
                )
            )

        dataframe = (
            self._build_dataframe(
                candles
            )
        )

        close = (
            dataframe[
                "close"
            ]
            .astype(
                float
            )
        )

        volume = (
            dataframe[
                "volume"
            ]
            .astype(
                float
            )
        )

        # ====================================================
        # EMA
        # ====================================================

        ema20_series = (
            self._ema(
                close,
                Config.EMA_FAST,
            )
        )

        ema50_series = (
            self._ema(
                close,
                Config.EMA_MEDIUM,
            )
        )

        ema200_series = (
            self._ema(
                close,
                Config.EMA_LONG,
            )
        )

        # ====================================================
        # RSI
        # ====================================================

        rsi_series = (
            self._rsi(
                close,
                Config.RSI_PERIOD,
            )
        )

        # ====================================================
        # CURRENT PRICE
        # ====================================================

        current_price = (
            self._series_value(
                close,
                -1,
            )
        )

        if current_price <= 0:

            raise (
                TechnicalMetricsError(
                    (
                        f"{normalized_symbol}: "
                        "invalid verified "
                        "current candle price."
                    )
                )
            )

        # ====================================================
        # HISTORICAL REFERENCES
        # ====================================================

        previous_1 = (
            self._series_value(
                close,
                -2,
            )
            if len(close) >= 2
            else 0.0
        )

        previous_5 = (
            self._series_value(
                close,
                -6,
            )
            if len(close) >= 6
            else 0.0
        )

        previous_20 = (
            self._series_value(
                close,
                -21,
            )
            if len(close) >= 21
            else 0.0
        )

        # ====================================================
        # MOMENTUM
        # ====================================================

        change_1d = (
            self._change_percent(
                current_price,
                previous_1,
            )
            if previous_1 > 0
            else 0.0
        )

        change_5d = (
            self._change_percent(
                current_price,
                previous_5,
            )
            if previous_5 > 0
            else 0.0
        )

        change_20d = (
            self._change_percent(
                current_price,
                previous_20,
            )
            if previous_20 > 0
            else 0.0
        )

        # ====================================================
        # EMA VALUES
        # ====================================================

        ema20_value = (
            self._series_value(
                ema20_series,
                -1,
            )
        )

        ema50_value = (
            self._series_value(
                ema50_series,
                -1,
            )
        )

        ema200_value = (
            self._series_value(
                ema200_series,
                -1,
            )
        )

        if (
            ema20_value <= 0
            or ema50_value <= 0
            or ema200_value <= 0
        ):

            raise (
                TechnicalMetricsError(
                    (
                        f"{normalized_symbol}: "
                        "verified EMA metrics "
                        "could not be calculated."
                    )
                )
            )

        # ====================================================
        # RSI VALUE
        # ====================================================

        rsi_value = (
            self._series_value(
                rsi_series,
                -1,
            )
        )

        if not (
            0.0
            <= rsi_value
            <= 100.0
        ):

            raise (
                TechnicalMetricsError(
                    (
                        f"{normalized_symbol}: "
                        "invalid RSI value."
                    )
                )
            )

        # ====================================================
        # VOLUME
        # ====================================================

        volume_average_series = (
            volume
            .rolling(
                window=(
                    Config
                    .VOLUME_AVG_PERIOD
                ),
                min_periods=(
                    Config
                    .VOLUME_AVG_PERIOD
                ),
            )
            .mean()
        )

        average_volume = (
            self._series_value(
                volume_average_series,
                -1,
            )
        )

        latest_volume = (
            self._series_value(
                volume,
                -1,
            )
        )

        if average_volume > 0:

            volume_ratio = (
                latest_volume
                / average_volume
            )

        else:

            # Missing/zero verified volume
            # must NOT be treated as strong volume.
            volume_ratio = 0.0

        # ====================================================
        # TREND
        # ====================================================

        above_ema20 = bool(
            current_price
            > ema20_value
        )

        above_ema50 = bool(
            current_price
            > ema50_value
        )

        above_ema200 = bool(
            current_price
            > ema200_value
        )

        ema20_above_ema50 = bool(
            ema20_value
            > ema50_value
        )

        ema50_above_ema200 = bool(
            ema50_value
            > ema200_value
        )

        bullish_ema_structure = bool(
            (
                current_price
                > ema20_value
            )
            and (
                ema20_value
                > ema50_value
            )
            and (
                ema50_value
                > ema200_value
            )
        )

        # ----------------------------------------------------
        # IMPORTANT
        #
        # stock_ranker.py and sector_scanner.py consume
        # the generic "bullish" field.
        #
        # Use the complete bullish EMA structure here.
        # ----------------------------------------------------

        bullish = (
            bullish_ema_structure
        )

        # ====================================================
        # RELATIVE STRENGTH
        # ====================================================

        benchmark_change = (
            safe_float(
                benchmark_change_pct,
                default=0.0,
            )
        )

        benchmark_change = float(
            benchmark_change
            or 0.0
        )

        relative_strength_pct = (
            change_20d
            - benchmark_change
        )

        # ====================================================
        # RETURN
        # ====================================================

        return {
            "symbol": (
                normalized_symbol
            ),

            # ------------------------------------------------
            # PRICE
            # ------------------------------------------------

            "current_price": round(
                current_price,
                2,
            ),

            # ------------------------------------------------
            # MOMENTUM
            # ------------------------------------------------

            "change_1d_pct": round(
                change_1d,
                4,
            ),

            "change_5d_pct": round(
                change_5d,
                4,
            ),

            "change_20d_pct": round(
                change_20d,
                4,
            ),

            # ------------------------------------------------
            # EMA
            # ------------------------------------------------

            "ema20": round(
                ema20_value,
                4,
            ),

            "ema50": round(
                ema50_value,
                4,
            ),

            "ema200": round(
                ema200_value,
                4,
            ),

            "above_ema20": (
                above_ema20
            ),

            "above_ema50": (
                above_ema50
            ),

            "above_ema200": (
                above_ema200
            ),

            "ema20_above_ema50": (
                ema20_above_ema50
            ),

            "ema50_above_ema200": (
                ema50_above_ema200
            ),

            "bullish_ema_structure": (
                bullish_ema_structure
            ),

            "bullish": (
                bullish
            ),

            # ------------------------------------------------
            # RSI
            # ------------------------------------------------

            "rsi": round(
                rsi_value,
                4,
            ),

            # ------------------------------------------------
            # VOLUME
            # ------------------------------------------------

            "latest_volume": round(
                latest_volume,
                2,
            ),

            "average_volume": round(
                average_volume,
                2,
            ),

            "volume_ratio": round(
                volume_ratio,
                4,
            ),

            # ------------------------------------------------
            # RELATIVE STRENGTH
            # ------------------------------------------------

            "benchmark_change_pct": round(
                benchmark_change,
                4,
            ),

            "relative_strength_pct": round(
                relative_strength_pct,
                4,
            ),

            # ------------------------------------------------
            # VERIFICATION
            # ------------------------------------------------

            "verified": True,

            "source": "FYERS",

            "candle_count": int(
                len(
                    dataframe
                )
            ),
        }

    # ========================================================
    # BUILD STOCK METRICS FROM FYERS
    # ========================================================

    def build_stock_metrics(
        self,
        access_token: str,
        *,
        symbol: str,
        mode: str,
        benchmark_change_pct: float = 0.0,
        force_refresh: bool = False,
    ) -> dict[str, Any]:

        normalized_symbol = (
            normalize_symbol(
                symbol
            )
        )

        if not normalized_symbol:

            raise ValueError(
                (
                    "Valid stock symbol "
                    "is required."
                )
            )

        normalized_mode = (
            Config
            .normalize_trading_mode(
                mode
            )
        )

        # ----------------------------------------------------
        # VERIFIED FYERS MARKET DATA
        # ----------------------------------------------------

        mode_data = (
            self
            .market_data_service
            .get_mode_market_data(
                access_token,
                normalized_symbol,
                mode=(
                    normalized_mode
                ),
                force_refresh=(
                    force_refresh
                ),
            )
        )

        if not isinstance(
            mode_data,
            dict,
        ):

            raise (
                TechnicalMetricsError(
                    (
                        f"{normalized_symbol}: "
                        "verified market-data "
                        "response is invalid."
                    )
                )
            )

        if not bool(
            mode_data.get(
                "verified"
            )
        ):

            raise (
                TechnicalMetricsError(
                    (
                        f"{normalized_symbol}: "
                        "unverified market data "
                        "was rejected."
                    )
                )
            )

        primary = (
            mode_data.get(
                "primary"
            )
        )

        if not isinstance(
            primary,
            list,
        ):

            raise (
                TechnicalMetricsError(
                    (
                        f"{normalized_symbol}: "
                        "verified primary candles "
                        "are unavailable."
                    )
                )
            )

        if not primary:

            raise (
                TechnicalMetricsError(
                    (
                        f"{normalized_symbol}: "
                        "verified primary candles "
                        "are unavailable."
                    )
                )
            )

        metrics = (
            self
            .build_metrics_from_candles(
                symbol=(
                    normalized_symbol
                ),
                candles=(
                    primary
                ),
                benchmark_change_pct=(
                    benchmark_change_pct
                ),
            )
        )

        metrics[
            "mode"
        ] = normalized_mode

        metrics[
            "primary_resolution"
        ] = (
            mode_data.get(
                "primary_resolution"
            )
            or Config
            .get_primary_resolution(
                normalized_mode
            )
        )

        metrics[
            "confirmation_resolution"
        ] = (
            mode_data.get(
                "confirmation_resolution"
            )
            or Config
            .get_confirmation_resolution(
                normalized_mode
            )
        )

        metrics[
            "market_data_verified"
        ] = True

        return metrics

    # ========================================================
    # BULK METRICS
    # ========================================================

    def build_metrics_for_stocks(
        self,
        access_token: str,
        stocks: Iterable[
            Any
        ],
        *,
        mode: str,
        benchmark_change_pct: float = 0.0,
        force_refresh: bool = False,
    ) -> dict[
        str,
        dict[str, Any],
    ]:
        """
        Build ranking metrics for many stocks.

        Accepts:

            NSEStock
            dict

        Returns:

            {
                "RELIANCE": {...},
                "HDFCBANK": {...},
                ...
            }

        Failed or unavailable symbols are skipped.

        IMPORTANT:
        No fallback fake metrics are generated.
        """

        normalized_mode = (
            Config
            .normalize_trading_mode(
                mode
            )
        )

        results: dict[
            str,
            dict[str, Any],
        ] = {}

        seen_symbols: set[
            str
        ] = set()

        success_count = 0
        failure_count = 0

        for stock in stocks:

            # ------------------------------------------------
            # SYMBOL
            # ------------------------------------------------

            if isinstance(
                stock,
                dict,
            ):

                raw_symbol = (
                    stock.get(
                        "symbol"
                    )
                )

            else:

                raw_symbol = getattr(
                    stock,
                    "symbol",
                    "",
                )

            symbol = (
                normalize_symbol(
                    raw_symbol
                )
            )

            if not symbol:
                continue

            if symbol in seen_symbols:
                continue

            seen_symbols.add(
                symbol
            )

            # ------------------------------------------------
            # BUILD
            # ------------------------------------------------

            try:

                metrics = (
                    self
                    .build_stock_metrics(
                        access_token,
                        symbol=(
                            symbol
                        ),
                        mode=(
                            normalized_mode
                        ),
                        benchmark_change_pct=(
                            benchmark_change_pct
                        ),
                        force_refresh=(
                            force_refresh
                        ),
                    )
                )

                # --------------------------------------------
                # HARD VERIFICATION
                # --------------------------------------------

                if not isinstance(
                    metrics,
                    dict,
                ):
                    failure_count += 1
                    continue

                if not bool(
                    metrics.get(
                        "verified"
                    )
                ):
                    failure_count += 1
                    continue

                current_price = (
                    safe_float(
                        metrics.get(
                            "current_price"
                        )
                    )
                )

                if (
                    current_price is None
                    or current_price <= 0
                ):
                    failure_count += 1
                    continue

                results[
                    symbol
                ] = metrics

                success_count += 1

            except Exception as exception:

                failure_count += 1

                log_exception(
                    logger,
                    (
                        "Technical metric "
                        "generation failed"
                    ),
                    exception=(
                        exception
                    ),
                    symbol=(
                        symbol
                    ),
                    component=(
                        "technical_metrics_service"
                    ),
                    error_code=(
                        "TECHNICAL_METRICS_FAILED"
                    ),
                    mode=(
                        normalized_mode
                    ),
                )

                continue

        logger.info(
            (
                "Technical metrics completed | "
                "mode=%s | requested=%s | "
                "success=%s | failed=%s"
            ),
            normalized_mode,
            len(
                seen_symbols
            ),
            success_count,
            failure_count,
        )

        return results

    # ========================================================
    # METRICS FOR ONE SYMBOL
    # ========================================================

    def get_metrics(
        self,
        access_token: str,
        *,
        symbol: str,
        mode: str,
        benchmark_change_pct: float = 0.0,
        force_refresh: bool = False,
    ) -> dict[str, Any]:

        return (
            self.build_stock_metrics(
                access_token,
                symbol=(
                    symbol
                ),
                mode=(
                    mode
                ),
                benchmark_change_pct=(
                    benchmark_change_pct
                ),
                force_refresh=(
                    force_refresh
                ),
            )
        )

    # ========================================================
    # HEALTH
    # ========================================================

    def health(
        self,
    ) -> dict[str, Any]:

        return {
            "service": (
                "Technical Metrics Service"
            ),

            "status": "healthy",

            "technical_only": True,

            "fake_data_allowed": bool(
                Config.ALLOW_FAKE_DATA
            ),

            "top_sectors": int(
                Config.TOP_SECTORS_COUNT
            ),

            "top_stocks_per_sector": int(
                Config.TOP_STOCKS_PER_SECTOR
            ),

            "max_candidate_universe": int(
                Config.MAX_SCANNER_UNIVERSE
            ),

            "supported_modes": list(
                Config
                .SUPPORTED_TRADING_MODES
            ),

            "ema_periods": [
                int(
                    Config.EMA_FAST
                ),
                int(
                    Config.EMA_MEDIUM
                ),
                int(
                    Config.EMA_LONG
                ),
            ],

            "rsi_period": int(
                Config.RSI_PERIOD
            ),

            "volume_average_period": int(
                Config
                .VOLUME_AVG_PERIOD
            ),

            "relative_strength_enabled": bool(
                Config
                .ENABLE_RELATIVE_STRENGTH
            ),

            "source": "FYERS",
        }


# ============================================================
# GLOBAL INSTANCE
# ============================================================


_global_technical_metrics_service: (
    TechnicalMetricsService | None
) = None


_global_technical_metrics_lock = (
    __import__(
        "threading"
    )
    .Lock()
)


# ============================================================
# GET SERVICE
# ============================================================


def get_technical_metrics_service(
) -> TechnicalMetricsService:

    global (
        _global_technical_metrics_service
    )

    if (
        _global_technical_metrics_service
        is not None
    ):

        return (
            _global_technical_metrics_service
        )

    with (
        _global_technical_metrics_lock
    ):

        if (
            _global_technical_metrics_service
            is None
        ):

            _global_technical_metrics_service = (
                TechnicalMetricsService()
            )

    return (
        _global_technical_metrics_service
    )
